// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNA-_4Tc9q_G2gWbtNxIJ8kBqeQvQpEHs',
    appId: '1:6367369154:web:77c6bbb8d0a05e9f46285b',
    messagingSenderId: '6367369154',
    projectId: 'libapp-82918',
    authDomain: 'libapp-82918.firebaseapp.com',
    storageBucket: 'libapp-82918.firebasestorage.app',
    measurementId: 'G-W03D1QFBK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqHohpnrD8BC9i6HJvveEmgAphBu69jT0',
    appId: '1:6367369154:android:6292b4b6dbbe599d46285b',
    messagingSenderId: '6367369154',
    projectId: 'libapp-82918',
    storageBucket: 'libapp-82918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7TsnE08F0U2RwoCZV-6WVDcTvdcbibsQ',
    appId: '1:6367369154:ios:8e4c0f72a3295fc846285b',
    messagingSenderId: '6367369154',
    projectId: 'libapp-82918',
    storageBucket: 'libapp-82918.firebasestorage.app',
    iosBundleId: 'com.example.libapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7TsnE08F0U2RwoCZV-6WVDcTvdcbibsQ',
    appId: '1:6367369154:ios:8e4c0f72a3295fc846285b',
    messagingSenderId: '6367369154',
    projectId: 'libapp-82918',
    storageBucket: 'libapp-82918.firebasestorage.app',
    iosBundleId: 'com.example.libapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNA-_4Tc9q_G2gWbtNxIJ8kBqeQvQpEHs',
    appId: '1:6367369154:web:4fcad488976d54bd46285b',
    messagingSenderId: '6367369154',
    projectId: 'libapp-82918',
    authDomain: 'libapp-82918.firebaseapp.com',
    storageBucket: 'libapp-82918.firebasestorage.app',
    measurementId: 'G-74XDVWE91E',
  );

}